export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const FETCH_FLIGHTS = 'FETCH_FLIGHTS';
export const FETCH_PASSENGERS = 'FETCH_PASSENGERS';
export const UPDATE_PASSENGER = 'UPDATE_PASSENGER';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';
export const MANAGE_PASSENGER = 'MANAGE_PASSENGER';
